/**
 * TITRE elements, end to end (issue #7, ADR 0004/0005/0006).
 *
 * A TITRE is an `EditingPlanElement` of `type: "title"` — the same catalogue
 * member the structural analysis can propose automatically, or a human can
 * add manually by picking a range in the document (`editing-plan.ts`'s
 * `createTitlePlanElement`). It anchors to segments of the approved script
 * rather than to the transcript's own text — adding one never rewrites a
 * word.
 *
 * Titles are rendered from a deterministic template, never generated by an
 * agent (ADR 0005: "templates and deterministic transformations for
 * editorial effects, creative generation only for B-roll scenes"), which is
 * why this whole module needs no model call and no Chromium — the only part
 * that touches a browser is the actual frame-stepped export, in
 * `steps/titles.ts`, via `render.ts`'s existing `exportScene`.
 */

import { esc, type OverlayScene } from "./fcpxml"
import type { Segment } from "./segments"
import type { EditingPlanElement, StyleGuide } from "../schemas"

/**
 * Standard title screen duration (issue #7's acceptance criteria). Fixed
 * rather than measured: unlike a B-roll scene, a title has no animation to
 * time itself against (see `renderTitleHtml`), so there is nothing to
 * measure — the spec's two seconds *is* the duration.
 */
export const TITLE_DURATION_SEC = 2

/* -------------------------------------------------------------------------- */
/* Rendering — a deterministic template, not a generated scene                */
/* -------------------------------------------------------------------------- */

/** Used when the style guide has no palette set yet. */
const FALLBACK_FOREGROUND = "#f5f5f5"

export type TitlePosition = "center" | "lower-third"

/**
 * The title screen's HTML, with CSS animations for dynamic entrance/exit.
 *
 * Animations use `animation-fill-mode: both` so the frame-stepping exporter
 * sees the correct state at t=0 and at the last frame. All motion is
 * CSS-only (no JS timing) — compatible with the Playwright frame-stepper.
 *
 * @param position - "center" (default full-screen title) or "lower-third"
 *   (persistent name/role overlay at bottom-left)
 */
export function renderTitleHtml(
  text: string,
  styleGuide: StyleGuide,
  position: TitlePosition = "center"
): string {
  const foreground = styleGuide.palette[1] ?? FALLBACK_FOREGROUND
  const accent = styleGuide.palette[2] ?? "#FF6B5A"
  const fontStack = styleGuide.fontStack || "system-ui, sans-serif"

  if (position === "lower-third") {
    return renderLowerThirdHtml(text, styleGuide)
  }

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>
      html, body {
        margin: 0;
        width: 1920px;
        height: 1080px;
        background: transparent;
      }
      body {
        display: flex;
        align-items: center;
        justify-content: center;
      }
      .title-container {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 16px;
        animation: containerIn 700ms cubic-bezier(0.16, 1, 0.3, 1) both;
      }
      .accent-bar {
        width: 80px;
        height: 4px;
        background: ${accent};
        border-radius: 2px;
        animation: barIn 500ms cubic-bezier(0.16, 1, 0.3, 1) 100ms both;
      }
      h1 {
        margin: 0;
        max-width: 1600px;
        font-family: ${fontStack};
        font-size: 96px;
        font-weight: 700;
        color: ${foreground};
        text-align: center;
        letter-spacing: -0.02em;
        line-height: 1.1;
        text-shadow: 0 2px 40px rgba(0, 0, 0, 0.3);
        animation: titleIn 600ms cubic-bezier(0.16, 1, 0.3, 1) 200ms both;
      }
      .subtitle {
        font-family: ${fontStack};
        font-size: 28px;
        font-weight: 400;
        color: ${foreground};
        opacity: 0.6;
        text-align: center;
        letter-spacing: 0.05em;
        text-transform: uppercase;
        animation: subtitleIn 500ms cubic-bezier(0.16, 1, 0.3, 1) 400ms both;
      }

      @keyframes containerIn {
        from { opacity: 0; transform: translateY(40px) scale(0.96); }
        to   { opacity: 1; transform: translateY(0) scale(1); }
      }
      @keyframes barIn {
        from { opacity: 0; transform: scaleX(0); }
        to   { opacity: 1; transform: scaleX(1); }
      }
      @keyframes titleIn {
        from { opacity: 0; transform: translateY(30px); }
        to   { opacity: 1; transform: translateY(0); }
      }
      @keyframes subtitleIn {
        from { opacity: 0; transform: translateY(20px); }
        to   { opacity: 0.6; transform: translateY(0); }
      }
    </style>
  </head>
  <body>
    <div class="title-container">
      <div class="accent-bar"></div>
      <h1>${esc(text)}</h1>
    </div>
  </body>
</html>
`
}

/**
 * Lower-third overlay: a compact name/role card anchored to bottom-left.
 *
 * Semi-transparent background with backdrop-filter blur, so the camera
 * footage shows through. Designed for 3–5s persistent display.
 */
function renderLowerThirdHtml(
  text: string,
  styleGuide: StyleGuide
): string {
  const foreground = styleGuide.palette[1] ?? FALLBACK_FOREGROUND
  const accent = styleGuide.palette[2] ?? "#FF6B5A"
  const fontStack = styleGuide.fontStack || "system-ui, sans-serif"

  const parts = text.split("|").map((s) => s.trim())
  const name = parts[0] ?? text
  const role = parts[1] ?? ""

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>
      html, body {
        margin: 0;
        width: 1920px;
        height: 1080px;
        background: transparent;
      }
      body {
        display: flex;
        align-items: flex-end;
        justify-content: flex-start;
        padding: 0 0 120px 100px;
      }
      .lower-third {
        display: flex;
        flex-direction: column;
        gap: 4px;
        padding: 20px 32px;
        background: rgba(0, 0, 0, 0.75);
        backdrop-filter: blur(20px);
        -webkit-backdrop-filter: blur(20px);
        border-left: 4px solid ${accent};
        border-radius: 0 8px 8px 0;
        animation: slideIn 500ms cubic-bezier(0.16, 1, 0.3, 1) both;
      }
      .name {
        font-family: ${fontStack};
        font-size: 36px;
        font-weight: 700;
        color: ${foreground};
        letter-spacing: -0.01em;
        line-height: 1.2;
      }
      .role {
        font-family: ${fontStack};
        font-size: 20px;
        font-weight: 400;
        color: ${foreground};
        opacity: 0.7;
        letter-spacing: 0.02em;
      }

      @keyframes slideIn {
        from { opacity: 0; transform: translateX(-40px); }
        to   { opacity: 1; transform: translateX(0); }
      }
    </style>
  </head>
  <body>
    <div class="lower-third">
      <div class="name">${esc(name)}</div>
      ${role ? `<div class="role">${esc(role)}</div>` : ""}
    </div>
  </body>
</html>
`
}

/* -------------------------------------------------------------------------- */
/* Compositing — reusing the existing FCPXML overlay machinery unchanged      */
/* -------------------------------------------------------------------------- */

/**
 * Projects a rendered TITRE element to the same `OverlayScene` shape a
 * B-roll scene is composited from (`fcpxml.ts`). Titles then get placed and
 * written into `timeline.fcpxml` by the exact same `placeOverlays`/
 * `buildFcpxml` a scene overlay goes through — nothing about compositing a
 * title is special enough to justify a parallel implementation.
 *
 * A title element has no `StoredScene` of its own to read a source file and
 * a start time off — those live on the `Segment` its `fromSegment` points
 * at, so the caller passes the segments it needs resolved against.
 */
export function titleElementToOverlayScene(
  element: EditingPlanElement,
  segments: Segment[]
): OverlayScene {
  if (element.exportPath == null) {
    throw new Error(
      `Title element ${element.id} has no exportPath yet — render it before compositing.`
    )
  }
  const segment = segments.find((s) => s.index === element.fromSegment)
  if (!segment) {
    throw new Error(
      `Title element ${element.id} anchors to segment ${element.fromSegment}, which no longer exists.`
    )
  }

  const isLowerThird = element.type === "lower-third"
  const durationSec = isLowerThird ? 4 : TITLE_DURATION_SEC

  return {
    id: element.id,
    planElementId: element.id,
    sourceFile: segment.file,
    scriptStart: segment.start,
    durationSec,
    exportPath: element.exportPath,
  }
}

/**
 * The title overlays a build of `timeline.fcpxml` would be handed.
 *
 * One definition of "ready to composite", shared by the `overlay` step that
 * writes the file and by the editing document that reports whether a title
 * made it in. Two copies of `approved && exportPath !== null` drifting apart
 * is exactly how the document ends up claiming a composition the export
 * doesn't contain.
 */
export function composableTitleOverlays(
  elements: EditingPlanElement[],
  segments: Segment[]
): OverlayScene[] {
  return elements
    .filter(
      (element) =>
        (element.type === "title" || element.type === "lower-third") &&
        element.status === "approved" &&
        element.exportPath != null
    )
    .map((element) => titleElementToOverlayScene(element, segments))
}
