/**
 * TITRE elements, end to end (issue #7, ADR 0004/0005/0006).
 *
 * A TITRE is an `EditingPlanElement` of `type: "title"` — the same catalogue
 * member the structural analysis can propose automatically, or a human can
 * add manually by picking a range in the document (`editing-plan.ts`'s
 * `createTitlePlanElement`). It anchors to segments of the approved script
 * rather than to the transcript's own text — adding one never rewrites a
 * word.
 *
 * Titles are rendered from a deterministic template, never generated by an
 * agent (ADR 0005: "templates and deterministic transformations for
 * editorial effects, creative generation only for B-roll scenes"), which is
 * why this whole module needs no model call and no Chromium — the only part
 * that touches a browser is the actual frame-stepped export, in
 * `steps/titles.ts`, via `render.ts`'s existing `exportScene`.
 */

import { esc, type OverlayScene } from "./fcpxml"
import type { Segment } from "./segments"
import { keptSegments } from "./segments"
import type { EditingPlanElement, Span, StyleGuide, TitleAnnotation } from "../schemas"

/**
 * Standard title screen duration (issue #7's acceptance criteria). Fixed
 * rather than measured: unlike a B-roll scene, a title has no animation to
 * time itself against (see `renderTitleHtml`), so there is nothing to
 * measure — the spec's two seconds *is* the duration.
 */
export const TITLE_DURATION_SEC = 2

/** Automatic title copy stays a label, not a second sentence on screen. */
export const TITLE_MAX_CHARS = 80

export function shortTitleText(value: string): string {
  const text = value.trim().replace(/\s+/g, " ")
  if (text.length <= TITLE_MAX_CHARS) return text

  const shortened = text.slice(0, TITLE_MAX_CHARS + 1)
  const boundary = shortened.lastIndexOf(" ")
  return shortened.slice(0, boundary > 0 ? boundary : TITLE_MAX_CHARS).trim()
}

/**
 * `globalThis.crypto`, not `node:crypto`.
 *
 * `createTitleAnnotation` runs in the browser — the cleanup review card calls
 * it directly — and importing `node:crypto` here made the bundler substitute
 * `crypto-browserify` (asn1, bignum, the lot) into the client chunk, about a
 * megabyte of polyfill to produce one id. The Web Crypto `randomUUID` is
 * present in every browser this app targets and in Node 19+, so both callers
 * get the same function with nothing bundled.
 */
function newAnnotationId(): string {
  return `title_${globalThis.crypto.randomUUID()}`
}

/* -------------------------------------------------------------------------- */
/* Creating an annotation                                                     */
/* -------------------------------------------------------------------------- */

export interface CreateTitleAnnotationInput {
  segments: Segment[]
  spans: Span[]
  segmentIndex: number
  text: string
}

/**
 * Anchors a new `TITRE` annotation to a segment of the approved script.
 *
 * Refuses two ways, and refuses without mutating anything: a segment index
 * that doesn't exist, and — the acceptance criterion this exists to
 * enforce — a segment that belongs to a cut span. The refusal never
 * restores that span; it just declines to anchor on top of it.
 */
export function createTitleAnnotation({
  segments,
  spans,
  segmentIndex,
  text,
}: CreateTitleAnnotationInput): TitleAnnotation {
  const segment = segments.find((candidate) => candidate.index === segmentIndex)
  if (!segment) {
    throw new Error(
      `No segment at index ${segmentIndex} — nothing to anchor the annotation to.`
    )
  }

  const kept = keptSegments(segments, spans)
  if (!kept.some((candidate) => candidate.index === segmentIndex)) {
    throw new Error(
      `Segment ${segmentIndex} belongs to a cut span. Restore the span before ` +
        "annotating it, or pick a target from the approved script."
    )
  }

  return {
    id: newAnnotationId(),
    segmentIndex,
    scriptStart: segment.start,
    scriptEnd: segment.end,
    sourceFile: segment.file,
    text,
    status: "pending",
    createdAt: new Date().toISOString(),
    htmlPath: null,
    exportPath: null,
  }
}

/* -------------------------------------------------------------------------- */
/* Reviewing an annotation                                                     */
/* -------------------------------------------------------------------------- */

export type TitleAnnotationDecision =
  | { action: "approve" }
  | { action: "reject" }
  | { action: "modify"; text: string }

/**
 * Applies a review decision.
 *
 * `modify` only ever edits the text — it never changes `status`, so an
 * edited annotation still needs an explicit accept or reject afterwards.
 * `approve` and `reject` are the only actions that move `status`.
 *
 * Changing the text drops `htmlPath`/`exportPath`. Without that, the copy on
 * screen and the copy in the rendered .mov silently disagree forever: the
 * `titles` step only renders annotations whose `exportPath` is still `null`
 * (`steps/titles.ts`), so an already-rendered title edited afterwards would
 * never be re-rendered and would composite with its old wording. Clearing the
 * paths is what makes "generated with the chosen copy" survive an edit.
 */
export function decideTitleAnnotation(
  annotation: TitleAnnotation,
  decision: TitleAnnotationDecision
): TitleAnnotation {
  switch (decision.action) {
    case "modify":
      if (decision.text === annotation.text) return annotation
      return {
        ...annotation,
        text: decision.text,
        htmlPath: null,
        exportPath: null,
      }

    case "approve":
      return { ...annotation, status: "approved" }

    case "reject":
      return { ...annotation, status: "rejected" }
  }
}

/* -------------------------------------------------------------------------- */
/* Rendering — a deterministic template, not a generated scene                */
/* -------------------------------------------------------------------------- */

/** Used when the style guide has no palette set yet. */
const FALLBACK_BACKGROUND = "#0a0a0a"
const FALLBACK_FOREGROUND = "#f5f5f5"

/**
 * The title screen's HTML, static and deterministic.
 *
 * Unlike a generated B-roll scene, this has no animation and no transparent
 * background: idea.md §5's "no background, no `setTimeout`" rules are for
 * scenes meant to overlay a transparent cutaway, but a title screen is
 * itself the full frame for its two seconds, so it paints an opaque
 * background from the style guide's palette. Authored at the same
 * 1920×1080 viewport `render.ts` expects everything else to be.
 */
export function renderTitleHtml(text: string, styleGuide: StyleGuide): string {
  const background = styleGuide.palette[0] ?? FALLBACK_BACKGROUND
  const foreground = styleGuide.palette[1] ?? FALLBACK_FOREGROUND
  const fontStack = styleGuide.fontStack || "system-ui, sans-serif"

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>
      html, body {
        margin: 0;
        width: 1920px;
        height: 1080px;
        background: ${background};
      }
      body {
        display: flex;
        align-items: center;
        justify-content: center;
      }
      h1 {
        margin: 0;
        max-width: 1600px;
        font-family: ${fontStack};
        font-size: 96px;
        font-weight: 700;
        color: ${foreground};
        text-align: center;
      }
    </style>
  </head>
  <body>
    <h1>${esc(text)}</h1>
  </body>
</html>
`
}

/* -------------------------------------------------------------------------- */
/* Compositing — reusing the existing FCPXML overlay machinery unchanged      */
/* -------------------------------------------------------------------------- */

/**
 * Projects a rendered TITRE element to the same `OverlayScene` shape a
 * B-roll scene is composited from (`fcpxml.ts`). Titles then get placed and
 * written into `timeline.fcpxml` by the exact same `placeOverlays`/
 * `buildFcpxml` a scene overlay goes through — nothing about compositing a
 * title is special enough to justify a parallel implementation.
 *
 * A title element has no `StoredScene` of its own to read a source file and
 * a start time off — those live on the `Segment` its `fromSegment` points
 * at, so the caller passes the segments it needs resolved against.
 */
export function titleElementToOverlayScene(
  element: EditingPlanElement,
  segments: Segment[]
): OverlayScene {
  if (element.exportPath == null) {
    throw new Error(
      `Title element ${element.id} has no exportPath yet — render it before compositing.`
    )
  }
  const segment = segments.find((s) => s.index === element.fromSegment)
  if (!segment) {
    throw new Error(
      `Title element ${element.id} anchors to segment ${element.fromSegment}, which no longer exists.`
    )
  }

  return {
    id: element.id,
    planElementId: element.id,
    sourceFile: segment.file,
    scriptStart: segment.start,
    durationSec: TITLE_DURATION_SEC,
    exportPath: element.exportPath,
  }
}

/**
 * The title overlays a build of `timeline.fcpxml` would be handed.
 *
 * One definition of "ready to composite", shared by the `overlay` step that
 * writes the file and by the editing document that reports whether a title
 * made it in. Two copies of `approved && exportPath !== null` drifting apart
 * is exactly how the document ends up claiming a composition the export
 * doesn't contain.
 */
export function composableTitleOverlays(
  elements: EditingPlanElement[],
  segments: Segment[]
): OverlayScene[] {
  return elements
    .filter(
      (element) =>
        element.type === "title" &&
        element.status === "approved" &&
        element.exportPath != null
    )
    .map((element) => titleElementToOverlayScene(element, segments))
}
