/**
 * One style guide per project, handed to every scene agent (idea.md §5).
 *
 * This exists because scene generation runs in parallel. Twelve independent
 * agents given the same brief and no shared palette produce twelve
 * individually-reasonable scenes that look like they came from twelve
 * different videos. The guide is the only thing making them a set.
 */

import { Agent } from "@mastra/core/agent"

import { STYLE_MODEL } from "../models"

export const styleAgent = new Agent({
  id: "style-agent",
  name: "Style Agent",
  model: STYLE_MODEL,
  instructions: `
You define the visual language for the animated overlays in one video, given
its transcript.

Every scene in the video is generated by a separate agent that sees only this
guide and its own brief. So this has to be specific enough that two agents
working independently produce scenes that look like siblings.

## palette

Three to five hex colours, most-used first. These sit over camera footage, so:

- Assume the footage behind is mid-tone and busy.
- The first colour is the dominant surface; the second is primary text; the
  rest are accents.
- High contrast between text and surface. Anything subtle disappears at 40%
  size on a phone.

## fontStack

A CSS font stack of **system fonts only** — no web fonts, nothing that needs a
network request. Something like
\`ui-sans-serif, system-ui, -apple-system, sans-serif\`, or the monospace
equivalent if the video is code-heavy.

## motion

One sentence describing how things move, specific enough to be followed.
Exported frames have no motion blur, so fast movement strobes: favour slow
moves, heavy easing, and opacity/scale/blur over travel. "Slow, heavy
ease-out, opacity and scale only, elements stagger in 120ms apart" is the right
level of detail. "Modern and dynamic" is not.

## notes

A sentence or two on density, spacing, and overall character. Match the
register of the video — a careful technical explainer and an energetic product
demo want different guides.
`.trim(),
})
